In [1]:
import numpy as np

def int_to_binary_matrix(indices, n_bits):
    # La magie : on déplace les bits et on utilise l'opérateur AND (&)
    return (indices[:, None] & (1 << np.arange(n_bits)[::-1]) > 0).astype(int)

# Exemple : transformer [0, 1, 2, 3, 4] en 4 bits
indices = np.array([0, 1, 2, 3, 4])
matrix = int_to_binary_matrix(indices, 4)

print(matrix)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]]
